---
title: "Quarterly State Tax Revenue Analysis"
author: "Don Boyd"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    toc: true
    toc_depth: 4
---

```{r, eval=FALSE, echo=FALSE}
# When we want a final report, run the following code selectively "by hand" (interactively) -- NEVER using Knit with eval=TRUE
rmdfn <- "E:\\Dropbox (Personal)\\RPrograms PC\\RevenueReport\\mainRevenueAnalysis.rmd"  # this file
outfn <- paste0("RevenueReport_", format(Sys.time(), "%Y-%m-%d"), ".html")
rmarkdown::render(rmdfn, output_format="html_document", output_file=outfn)

# I have tried MANY approaches to writing the rendered file to a different directory, but they have not worked.
# outdir <- "E:\\RIG\\SRR\\"
# rmarkdown::render("E:\\Dropbox (Personal)\\RPrograms PC\\RevenueReport\\mainRevenueAnalysis.rmd", output_format="html_document", output_file=outfn, output_dir=outdir, intermediates_dir=outdir)

```


```{r defines, echo=FALSE}

qtd <- paste0(sdatd, "Data for ongoing work\\qtax rfiles\\")
# qtdrop <- "C:\\Users\\Don\\Dropbox (Personal)\\R items\\qtax\\"
qtdrop <- "E:\\Dropbox (Personal)\\R items\\qtax\\"
 
```


```{r loads, echo=FALSE, message=FALSE}
library(btools) # library that I created (install from github)
library(foreign) # various import and export routines - e.g., for reading Stata files
library(gdata) # for reading spreadsheets
library(ggplot2)
library(scales) # so we can use scales with ggplot2
library(plyr) # needed for ddply [but was it already loaded??]
library(reshape2)
library(tidyr)
library(dplyr) # always load AFTER plyr
library(knitr)
library(lubridate)
library(stringr)
library(grDevices)

# sessionInfo()

```


```{r updateapidata, eval=FALSE, echo=FALSE}
# only run this when Census has updated the quarterly tax data
source("getupdatedqtaxfromapi.r", echo=TRUE) 

```


```{r combineapihist, eval=FALSE, echo=FALSE}
# only run this when Census has updated the quarterly tax data
source("combineqtaxhistapi.r", echo=TRUE) 

```


```{r prepdata, eval=FALSE, echo=FALSE}
# only run this when Census has updated the quarterly tax data
# or when I want to add to the variables and information we want to analyze
# get price index, compute real, and compute ma4 and maybe pchya
source("prepdata.r", echo=TRUE) 
```



```{r getbasedata, echo=FALSE, message=FALSE, warning=FALSE, cache=TRUE}
# library(hts) #  Hierarchical and grouped time series
# get the main file once, centrally, and all subprograms can use this
qtax <- readRDS(file=paste0(qtd, "qtaxrma.rds"))

# ht(qtax)
# count(qtax, c("vname", "ic", "vdesc"))

# make long file, get pchyas and diff from 2007-10-01

dfs <- qtax %>% gather(valtype, taxval, value, rvalue, valma4, rvalma4) %>%
  mutate(stname=getstname(stabbr), 
         region=as.character(factor(stabbr, levels=stcodes$stabbr, labels=stcodes$beargn.name)),
         geotype="state") %>%
  arrange(valtype, stabbr, vname, level, date)
# ht(dfs)
# now create a non-(iit, gst, cit) value
xigc <- dfs %>% filter(vname %in% c("tottax", "iit", "gst", "cit")) %>% 
  select(-vdesc, -ic) %>%
  spread(vname, taxval) %>%
  mutate(taxval=tottax - naz(iit) - naz(gst) - naz(cit), 
         vname="xigc", vdesc="Total tax excluding iit, gst, and cit") %>%
  select(-cit, -gst, - iit, -tottax)
# ht(xigc)
# subset(dfs, stabbr=="AK" & date=="1963-01-01" & valtype=="value") # ah, there is no "tottax" before 1977-01-01 
# count(subset(dfs, stabbr=="NY" & valtype=="value"), c("vname", "date"))

# create region-level summaries and add them to the data before calcing pdiff and pchya
dfs2 <- rbind.fill(dfs, xigc)
rm(dfs, xigc)

dfr <- dfs2 %>% group_by(valtype, region, vname, level, date) %>%
  summarise(taxval=sum(taxval, na.rm=TRUE)) %>%
  mutate(geotype="region")

dfl <- rbind.fill(dfs2, dfr)
rm(dfs2, dfr)

idx <- with(dfl, match(paste(geotype, region, stabbr, "2007-10-01", level, valtype, vname),
                       paste(geotype, region, stabbr, date, level, valtype, vname)))
dfl$pdiff <- with(dfl, taxval / taxval[idx] * 100 - 100)

idx <- with(dfl, match(paste(geotype, region, stabbr, date - years(1), level, valtype, vname),
                       paste(geotype, region, stabbr, date, level, valtype, vname)))
dfl$pchya <- with(dfl, taxval / taxval[idx] * 100 - 100)

# get state neighbors
nb <- readRDS(paste0(qtd, "stateneighbors.rds"))

lq <- max(dfl$date)
```




```{r intro, child=paste0("subIntro.rmd"), eval=TRUE}
# don't put anything else here - it WILL NOT BE RUN!
```


```{r maps, child=paste0("subMaps.rmd"), eval=TRUE}
# don't put anything else here - it WILL NOT BE RUN!
```



```{r eval=FALSE, echo=FALSE, message=FALSE}

#****************************************************************************************************
#
#                Mess around ####
#
#***************************************************************************************************

The process is actually pretty simple. It is as follows assuming you have already set up a local github repository in Rstudio.

go to github.com and click repositories and new repository
Give the repository a name and description and create it
Follow the instructions to “push an existing repository from the command line”
For example if the repository was called foo, the commands would be:

git remote add origin https://github.com/donboyd5/RevenueReport.git
git push -u origin master

Thus, in Rstudio, you could open the shell while in your project. This would ensure that the shell is open in the working directory of your project, and then run the previous commands (naturally with the correct repository name) .

The only final problem I encountered was that I had not used github for a while and github did not have my SSH key. So I needed to add my SSH key to github. To do this:

In Rstudio click “preferences” and “view public key” and copy the whole key to the clipboard
In Github, click “edit user profile” and “SSH keys” and add the key.

```

