---
title: "subIntro"
author: "Don Boyd"

---

```{r}
# qtax <- readRDS(file=paste0(qtd, "qtaxrma.rds"))
# ht(qtax)
# count(qtax, c("vname", "ic", "vdesc"))


# make long file, get pchyas and diff from 2007-10-01 then graph
<<<<<<< HEAD

dfs <- qtax %>% gather(valtype, taxval, value, rvalue, valma4, rvalma4) %>%
  mutate(stname=getstname(stabbr), 
         region=as.character(factor(stabbr, levels=stcodes$stabbr, labels=stcodes$beargn.name)),
         geotype="state") %>%
  arrange(valtype, stabbr, vname, level, date)
ht(dfs)
# create region-level summaries and add them to the data before calcing pdiff and pchya

dfr <- dfs %>% group_by(valtype, region, vname, level, date) %>%
  summarise(taxval=sum(taxval, na.rm=TRUE)) %>%
  mutate(geotype="region")

dfl <- rbind.fill(dfs, dfr)

idx <- with(dfl, match(paste(geotype, region, stabbr, "2007-10-01", level, valtype, vname),
                       paste(geotype, region, stabbr, date, level, valtype, vname)))
dfl$pdiff <- with(dfl, taxval / taxval[idx] * 100 - 100)

idx <- with(dfl, match(paste(geotype, region, stabbr, date - years(1), level, valtype, vname),
                       paste(geotype, region, stabbr, date, level, valtype, vname)))
=======
dfl <- qtax %>% gather(valtype, taxval, value, rvalue, valma4, rvalma4) %>%
  arrange(valtype, stabbr, vname, level, date)
ht(dfl)
idx <- with(dfl, match(paste(stabbr, "2007-10-01", level, valtype, vname),
                       paste(stabbr, date, level, valtype, vname)))
dfl$pdiff <- with(dfl, taxval / taxval[idx] * 100 - 100)

idx <- with(dfl, match(paste(stabbr, date - years(1), level, valtype, vname),
                       paste(stabbr, date, level, valtype, vname)))
>>>>>>> 10548340705b5568eef057271bcb1c5571475621
dfl$pchya <- with(dfl, taxval / taxval[idx] * 100 - 100)

# get state neighbors
nb <- readRDS(paste0(qtd, "stateneighbors.rds"))

lq <- max(dfl$date)
```


# Pchya
## Latest quarter (beginning `r lq`), total tax, ranked
```{r}

tab <- dfl %>% filter(vname=="tottax" & level=="sg" & valtype=="value" & date==lq)
tab <- tab %>% arrange(-pchya) %>% select(stabbr, pchya)
kable(tab, digits=2)

```





# Some plots of taxes
## 4q MA of real taxes by type, indexed to recession start, US
```{r}
txs <- c("tottax", "iit", "gst", "cit")
qplot(date, pdiff, data=dfl %>%
        filter(stabbr=="US" & level=="sg" & date>="2007-10-01" & vname %in% txs & valtype=="rvalma4"),
        colour=vname, geom=c("point", "line")) + geom_hline(y=0)

```


## 4q MA of real total taxes for selected states, indexed to recession start
```{r}
txs <- c("tottax")
sts <- c("US", "CA", "NY", "TX", "FL")
qplot(date, pdiff, data=dfl %>%
        filter(stabbr %in% sts & level=="sg" & date>="2007-10-01" & vname %in% txs & valtype=="rvalma4"),
        colour=stabbr, geom=c("point", "line")) + geom_hline(y=0)

sts <- c("US", "NJ", "KS", "IL", "SC")
qplot(date, pdiff, data=dfl %>%
        filter(stabbr %in% sts & level=="sg" & date>="2007-10-01" & vname %in% txs & valtype=="rvalma4"),
        colour=stabbr, geom=c("point", "line")) + geom_hline(y=0)

# get a state and its neighbors
st <- "IL"
sts <- c(st, nb[nb$stabbr==st, "nstabbr"])
qplot(date, pdiff, data=dfl %>%
        filter(stabbr %in% sts & level=="sg" & date>="2007-10-01" & vname %in% txs & valtype=="rvalma4"),
        colour=stabbr, geom=c("point", "line")) + geom_hline(y=0)



```

